---
parent: 'test_cases/test_pull_request_crio_integration_rhel.yml'
overrides:
  provision:
    os: "fedora-cgroupv2"
    stage: "crio"
    provider: "aws"
  evars: "-e build_crun=true -e build_runc=false -e cgroupv2=true"
